; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.12"

; RedHen Module Suite
projects[redhen][type] = "module"
projects[redhen][subdir] = "redhen"
projects[redhen][download][type] = "git"
projects[redhen][download][url] = "git://git.drupal.org/project/redhen.git"
projects[redhen][download][branch] = "master"

; RedHen Dependencies
projects[relation][subdir] = "contrib"
projects[entity][subdir] = "contrib"
projects[ctools] = "1.x-dev"
projects[ctools][subdir] = "contrib"
projects[registration][subdir] = "contrib"

; Additional Contrib Modules and Themes (Not Required)
projects[] = admin_menu
projects[features][subdir] = "contrib"
projects[rules][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[strongarm][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[adaptivetheme][type] = "theme"
projects[at-commerce][type] = "theme"

; Developer Tools
projects[devel][subdir] = "developer"
projects[diff][subdir] = "developer"
